apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BhdXRoLXBvc3RncmVzLnRvZ2dsZW1hc3Rlci5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2F1dGhfZGI=
  MASTER_KEY: YWRtaW4tc2VjcmV0by0xMjM=
  PORT: OA==
