apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: togglemaster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: 982599766065.dkr.ecr.us-east-1.amazonaws.com/togglemaster-analytics:latest
          ports:
            - containerPort: 8005
          env:
            - name: DYNAMODB_TABLE_NAME
              value: "ToggleMasterAnalytics"
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: SQS_QUEUE_URL
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: togglemaster
spec:
  selector:
    app: analytics
  ports:
    - port: 8005
      targetPort: 8005
