apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0B0YXJnZXRpbmctcG9zdGdyZXMudG9nZ2xlbWFzdGVyLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvdGFyZ2V0aW5nX2Ri
