apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
data:
  REDIS_URL: cmVkaXNzOi8vbWFzdGVyLnRvZ2dsZW1hc3Rlci1yZWRpcy1jYWNoZS5ocmVhZXkudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vNjk3NjgzNzU1MTA0L3RvZ2dsZW1hc3Rlci1ldmVudHM=
  SERVICE_API_KEY: c2VydmljZS1rZXktbG9jYWwtMTIz
