name: auth-service

on:
  push:
    branches: [main]
    paths:
      - 'services/auth/**'
      - '.github/workflows/go-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'services/auth/**'
      - '.github/workflows/go-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/go-ci.yml
    with:
      service_dir: auth
      service_name: auth-service
    secrets: inherit
